//
//  ViewController.swift
//  screen_2_intro_
//
//  Created by exportkit on 2023.
//  Copyright (c)  exportkit. All rights reserved.
//  Generated by Export Kit v128
//
	
import UIKit
	
class screen_2_intro__ViewController: UIViewController {

    
	@IBOutlet weak var _bg__screen_2_intro__ek2: UIView!
	@IBOutlet weak var _3d_rendering_paper_bill_transaction_receipt_payment_icon_png: UIView!
	@IBOutlet weak var c689ace4a88633ae25d296d62f6116cb: UIImageView!
	@IBOutlet weak var forms_button_container_: UIView!
	@IBOutlet weak var mask_group_1: UIImageView!
	@IBOutlet weak var esi_logoicon_finalsblue: UIImageView!
	@IBOutlet weak var c689ace4a88633ae25d296d62f6116cb_ek1: UIImageView!
	@IBOutlet weak var _89af49bcdeb075f12da2314661da3755: UIImageView!
	@IBOutlet weak var _3d_rendering_paper_bill_transaction_receipt_payment_icon_png_ek1: UIView!
	@IBOutlet weak var forms: UILabel!
	@IBOutlet weak var plus_icon_3d_render_free_vector: UIView!
	@IBOutlet weak var _4ee67baadb026a533fdc4e4cbe73e64a: UIImageView!
	@IBOutlet weak var rectangle_94: UIView!
	@IBOutlet weak var image_2: UIImageView!
	@IBOutlet weak var a286c0a5599ce27c5d409b1fa05a9c03: UIImageView!
	@IBOutlet weak var new_email_notification_3d_icon_3d_realistic_email_icon_3d_vector_email_580446_380: UIView!
	@IBOutlet weak var cd05c4ed74d0ef7858cf235a35986d38: UIImageView!
	@IBOutlet weak var image_1: UIImageView!
	@IBOutlet weak var welcome: UILabel!
	@IBOutlet weak var timekeeping: UILabel!
	@IBOutlet weak var paystubs_____w_2: UILabel!
	@IBOutlet weak var benefits: UILabel!
	@IBOutlet weak var _401k: UILabel!
	@IBOutlet weak var pay_schedule: UILabel!
	@IBOutlet weak var call_us: UILabel!
	@IBOutlet weak var email_us: UILabel!
	@IBOutlet weak var _44d42e84ce0d2bf6b36165c4e3436efc: UIImageView!
	@IBOutlet weak var feedback: UILabel!
	@IBOutlet weak var png_transparent_computer_icons_profit_encapsulated_postscript_finance_text_people_logo: UIImageView!
	@IBOutlet weak var rectangle: UIView!
	@IBOutlet weak var buttons_container_: UIView!
	
    override func viewDidLoad() {
        super.viewDidLoad()

	

        // Do any additional setup after loading the view, typically from a nib.
    }

    
	
}
